title: MilanovicMihael
author: "Mihael Milanovic"
description: "Original character gallery of Mihael Milanovic."
url: "https://milanovic-mihael.github.io" 
baseurl: "" 

markdown: kramdown
highlighter: rouge 
exclude: [ "node_modules", "vendor", "Gemfile", "Gemfile.lock" ]

collections:
  ocs:
    output: true
    permalink: /oc/:name/

defaults:
  - scope:
      path: ""
      type: "ocs"
    values:
      layout: "oc"

plugins:
  - jekyll-sitemap